/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  EmailLoginRequest,
  HTTPValidationError,
  OAuthLoginRequest,
  RefreshTokenRequest,
  RegisterRequest,
  SessionExchangeRequest,
  TokenResponse,
  UserResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




/**
 * Register with email/password and issue backend tokens.
 * @summary Register
 */
export const useRegisterApiAuthRegisterPostHook = () => {
        const registerApiAuthRegisterPost = useCustomInstance<TokenResponse>();

        return useCallback((
    registerRequest: RegisterRequest,
 signal?: AbortSignal
) => {
        return registerApiAuthRegisterPost(
          {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
          );
        }, [registerApiAuthRegisterPost])
      }



export const useRegisterApiAuthRegisterPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,{data: RegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['registerApiAuthRegisterPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const registerApiAuthRegisterPost =  useRegisterApiAuthRegisterPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerApiAuthRegisterPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterApiAuthRegisterPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>>
    export type RegisterApiAuthRegisterPostMutationBody = RegisterRequest
    export type RegisterApiAuthRegisterPostMutationError = HTTPValidationError

    /**
 * @summary Register
 */
export const useRegisterApiAuthRegisterPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,{data: RegisterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(useRegisterApiAuthRegisterPostMutationOptions(options), queryClient);
    }
    /**
 * Login with OAuth or email/password and issue backend tokens.

Verify OAuth token, create/update user, and issue JWE tokens.
 * @summary Login
 */
export const useLoginApiAuthLoginPostHook = () => {
        const loginApiAuthLoginPost = useCustomInstance<TokenResponse>();

        return useCallback((
    oAuthLoginRequestEmailLoginRequest: OAuthLoginRequest | EmailLoginRequest,
 signal?: AbortSignal
) => {
        return loginApiAuthLoginPost(
          {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: oAuthLoginRequestEmailLoginRequest, signal
    },
          );
        }, [loginApiAuthLoginPost])
      }



export const useLoginApiAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest | EmailLoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest | EmailLoginRequest}, TContext> => {

const mutationKey = ['loginApiAuthLoginPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const loginApiAuthLoginPost =  useLoginApiAuthLoginPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, {data: OAuthLoginRequest | EmailLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginApiAuthLoginPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>>
    export type LoginApiAuthLoginPostMutationBody = OAuthLoginRequest | EmailLoginRequest
    export type LoginApiAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginApiAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,{data: OAuthLoginRequest | EmailLoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>,
        TError,
        {data: OAuthLoginRequest | EmailLoginRequest},
        TContext
      > => {
      return useMutation(useLoginApiAuthLoginPostMutationOptions(options), queryClient);
    }
    /**
 * Exchange better-auth session token for backend JWE tokens.

Used by email/password auth users who have no OAuth provider token.
Verifies session with better-auth server, then issues backend tokens.
 * @summary Session Exchange
 */
export const useSessionExchangeApiAuthSessionExchangePostHook = () => {
        const sessionExchangeApiAuthSessionExchangePost = useCustomInstance<TokenResponse>();

        return useCallback((
    sessionExchangeRequest: SessionExchangeRequest,
 signal?: AbortSignal
) => {
        return sessionExchangeApiAuthSessionExchangePost(
          {url: `/api/auth/session-exchange`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sessionExchangeRequest, signal
    },
          );
        }, [sessionExchangeApiAuthSessionExchangePost])
      }



export const useSessionExchangeApiAuthSessionExchangePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>, TError,{data: SessionExchangeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>, TError,{data: SessionExchangeRequest}, TContext> => {

const mutationKey = ['sessionExchangeApiAuthSessionExchangePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const sessionExchangeApiAuthSessionExchangePost =  useSessionExchangeApiAuthSessionExchangePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>, {data: SessionExchangeRequest}> = (props) => {
          const {data} = props ?? {};

          return  sessionExchangeApiAuthSessionExchangePost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SessionExchangeApiAuthSessionExchangePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>>
    export type SessionExchangeApiAuthSessionExchangePostMutationBody = SessionExchangeRequest
    export type SessionExchangeApiAuthSessionExchangePostMutationError = HTTPValidationError

    /**
 * @summary Session Exchange
 */
export const useSessionExchangeApiAuthSessionExchangePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>, TError,{data: SessionExchangeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useSessionExchangeApiAuthSessionExchangePostHook>>>,
        TError,
        {data: SessionExchangeRequest},
        TContext
      > => {
      return useMutation(useSessionExchangeApiAuthSessionExchangePostMutationOptions(options), queryClient);
    }
    /**
 * Refresh access token using refresh token.
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshPostHook = () => {
        const refreshTokenApiAuthRefreshPost = useCustomInstance<TokenResponse>();

        return useCallback((
    refreshTokenRequest: RefreshTokenRequest,
 signal?: AbortSignal
) => {
        return refreshTokenApiAuthRefreshPost(
          {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest, signal
    },
          );
        }, [refreshTokenApiAuthRefreshPost])
      }



export const useRefreshTokenApiAuthRefreshPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext> => {

const mutationKey = ['refreshTokenApiAuthRefreshPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const refreshTokenApiAuthRefreshPost =  useRefreshTokenApiAuthRefreshPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, {data: RefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  refreshTokenApiAuthRefreshPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenApiAuthRefreshPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>>
    export type RefreshTokenApiAuthRefreshPostMutationBody = RefreshTokenRequest
    export type RefreshTokenApiAuthRefreshPostMutationError = HTTPValidationError

    /**
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,{data: RefreshTokenRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>,
        TError,
        {data: RefreshTokenRequest},
        TContext
      > => {
      return useMutation(useRefreshTokenApiAuthRefreshPostMutationOptions(options), queryClient);
    }
    /**
 * Logout endpoint.

Client should remove tokens from localStorage.
 * @summary Logout
 */
export const useLogoutApiAuthLogoutPostHook = () => {
        const logoutApiAuthLogoutPost = useCustomInstance<void>();

        return useCallback((

 signal?: AbortSignal
) => {
        return logoutApiAuthLogoutPost(
          {url: `/api/auth/logout`, method: 'POST', signal
    },
          );
        }, [logoutApiAuthLogoutPost])
      }



export const useLogoutApiAuthLogoutPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext> => {

const mutationKey = ['logoutApiAuthLogoutPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const logoutApiAuthLogoutPost =  useLogoutApiAuthLogoutPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, void> = () => {


          return  logoutApiAuthLogoutPost()
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutApiAuthLogoutPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>>

    export type LogoutApiAuthLogoutPostMutationError = unknown

    /**
 * @summary Logout
 */
export const useLogoutApiAuthLogoutPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(useLogoutApiAuthLogoutPostMutationOptions(options), queryClient);
    }
    /**
 * Return the current authenticated user.
 * @summary Get Me
 */
export const useGetMeApiAuthMeGetHook = () => {
        const getMeApiAuthMeGet = useCustomInstance<UserResponse>();

        return useCallback((

 signal?: AbortSignal
) => {
        return getMeApiAuthMeGet(
          {url: `/api/auth/me`, method: 'GET', signal
    },
          );
        }, [getMeApiAuthMeGet])
      }




export const getGetMeApiAuthMeGetInfiniteQueryKey = () => {
    return [
    'infinite', `/api/auth/me`
    ] as const;
    }

export const getGetMeApiAuthMeGetQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const useGetMeApiAuthMeGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiAuthMeGetInfiniteQueryKey();

  const getMeApiAuthMeGet =  useGetMeApiAuthMeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>> = ({ signal }) => getMeApiAuthMeGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiAuthMeGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>
export type GetMeApiAuthMeGetInfiniteQueryError = unknown


export function useGetMeApiAuthMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiAuthMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetMeApiAuthMeGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetMeApiAuthMeGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiAuthMeGetQueryKey();

  const getMeApiAuthMeGet =  useGetMeApiAuthMeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>> = ({ signal }) => getMeApiAuthMeGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiAuthMeGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>
export type GetMeApiAuthMeGetQueryError = unknown


export function useGetMeApiAuthMeGet<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGet<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGet<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiAuthMeGet<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetMeApiAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const useGetMeApiAuthMeGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiAuthMeGetQueryKey();

  const getMeApiAuthMeGet =  useGetMeApiAuthMeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>> = ({ signal }) => getMeApiAuthMeGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiAuthMeGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>
export type GetMeApiAuthMeGetSuspenseQueryError = unknown


export function useGetMeApiAuthMeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiAuthMeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetMeApiAuthMeGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




