/**
 * Generated by orval 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import {
  queryOptions as queryOptionsBuilder,
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  EmailLoginRequest,
  HTTPValidationError,
  OAuthExchangeRequest,
  OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams,
  OauthCallbackApiAuthOauthProviderCallbackGetParams,
  PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost200,
  PasskeyAuthenticationOptionsRequest,
  PasskeyAuthenticationVerifyRequest,
  PasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost200,
  PasskeyRegistrationVerifyRequest,
  RefreshTokenRequest,
  RegisterRequest,
  TokenResponse,
  UserResponse
} from '../model';

import { useCustomInstance } from '../../../hooks/use-custom-instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Register with email/password and issue backend tokens.
 * @summary Register
 */
export const useRegisterApiAuthRegisterPostHook = () => {
        const registerApiAuthRegisterPost = useCustomInstance<TokenResponse>();

        return useCallback((
    registerRequest: RegisterRequest,
 signal?: AbortSignal
) => {


        return registerApiAuthRegisterPost(
          {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
          );
        }, [registerApiAuthRegisterPost])
      }




export const getRegisterApiAuthRegisterPostMutationKey = () => ['registerApiAuthRegisterPost'] as const;

export const useRegisterApiAuthRegisterPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,RegisterApiAuthRegisterPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,RegisterApiAuthRegisterPostMutationVariables, TContext> => {

const mutationKey = getRegisterApiAuthRegisterPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const registerApiAuthRegisterPost =  useRegisterApiAuthRegisterPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, RegisterApiAuthRegisterPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  registerApiAuthRegisterPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterApiAuthRegisterPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>>
    export type RegisterApiAuthRegisterPostMutationBody = RegisterRequest
    export type RegisterApiAuthRegisterPostMutationError = HTTPValidationError
    export type RegisterApiAuthRegisterPostMutationVariables = {data: RegisterRequest}

    /**
 * @summary Register
 */
export const useRegisterApiAuthRegisterPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>, TError,RegisterApiAuthRegisterPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRegisterApiAuthRegisterPostHook>>>,
        TError,
        RegisterApiAuthRegisterPostMutationVariables,
        TContext
      > => {
      return useMutation(useRegisterApiAuthRegisterPostMutationOptions(options), queryClient);
    }
    /**
 * Login with email/password and issue first-party tokens.
 * @summary Login
 */
export const useLoginApiAuthLoginPostHook = () => {
        const loginApiAuthLoginPost = useCustomInstance<TokenResponse>();

        return useCallback((
    emailLoginRequest: EmailLoginRequest,
 signal?: AbortSignal
) => {


        return loginApiAuthLoginPost(
          {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailLoginRequest, signal
    },
          );
        }, [loginApiAuthLoginPost])
      }




export const getLoginApiAuthLoginPostMutationKey = () => ['loginApiAuthLoginPost'] as const;

export const useLoginApiAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,LoginApiAuthLoginPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,LoginApiAuthLoginPostMutationVariables, TContext> => {

const mutationKey = getLoginApiAuthLoginPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const loginApiAuthLoginPost =  useLoginApiAuthLoginPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, LoginApiAuthLoginPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  loginApiAuthLoginPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>>
    export type LoginApiAuthLoginPostMutationBody = EmailLoginRequest
    export type LoginApiAuthLoginPostMutationError = HTTPValidationError
    export type LoginApiAuthLoginPostMutationVariables = {data: EmailLoginRequest}

    /**
 * @summary Login
 */
export const useLoginApiAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>, TError,LoginApiAuthLoginPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useLoginApiAuthLoginPostHook>>>,
        TError,
        LoginApiAuthLoginPostMutationVariables,
        TContext
      > => {
      return useMutation(useLoginApiAuthLoginPostMutationOptions(options), queryClient);
    }
    /**
 * Start an OAuth Authorization Code + PKCE transaction.
 * @summary Oauth Authorize
 */
export const useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook = () => {
        const oauthAuthorizeApiAuthOauthProviderAuthorizeGet = useCustomInstance<unknown>();

        return useCallback((
    provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams,
 signal?: AbortSignal
) => {


        return oauthAuthorizeApiAuthOauthProviderAuthorizeGet(
          {url: `/api/auth/oauth/${provider}/authorize`, method: 'GET',
        params, signal
    },
          );
        }, [oauthAuthorizeApiAuthOauthProviderAuthorizeGet])
      }




export const getOauthAuthorizeApiAuthOauthProviderAuthorizeGetInfiniteQueryKey = (provider: 'google' | 'github' | 'facebook',
    params?: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams,) => {
    return [
    'infinite', `/api/auth/oauth/${provider}/authorize`, ...(params ? [params] : [])
    ] as const;
    }

export const getOauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryKey = (provider: 'google' | 'github' | 'facebook',
    params?: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams,) => {
    return [
    `/api/auth/oauth/${provider}/authorize`, ...(params ? [params] : [])
    ] as const;
    }


export const useOauthAuthorizeApiAuthOauthProviderAuthorizeGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>>, TError = HTTPValidationError>(provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthAuthorizeApiAuthOauthProviderAuthorizeGetInfiniteQueryKey(provider,params);

  const oauthAuthorizeApiAuthOauthProviderAuthorizeGet =  useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>> = ({ signal }) => oauthAuthorizeApiAuthOauthProviderAuthorizeGet(provider,params, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OauthAuthorizeApiAuthOauthProviderAuthorizeGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>>
export type OauthAuthorizeApiAuthOauthProviderAuthorizeGetInfiniteQueryError = HTTPValidationError


export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Oauth Authorize
 */

export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useOauthAuthorizeApiAuthOauthProviderAuthorizeGetInfiniteQueryOptions(provider,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const useOauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryKey(provider,params);

  const oauthAuthorizeApiAuthOauthProviderAuthorizeGet =  useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>> = ({ signal }) => oauthAuthorizeApiAuthOauthProviderAuthorizeGet(provider,params, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>>
export type OauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryError = HTTPValidationError


export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGet<TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGet<TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGet<TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Oauth Authorize
 */

export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGet<TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useOauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryOptions(provider,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const useOauthAuthorizeApiAuthOauthProviderAuthorizeGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryKey(provider,params);

  const oauthAuthorizeApiAuthOauthProviderAuthorizeGet =  useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>> = ({ signal }) => oauthAuthorizeApiAuthOauthProviderAuthorizeGet(provider,params, signal);





   return  queryOptionsBuilder({ queryKey, ...queryOptions, queryFn: queryOptions?.queryFn ?? queryFn}) as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> } & { throwOnError?: ((this: never, error: TError) => boolean) & { readonly __inferenceOnly: never } }
}

export type OauthAuthorizeApiAuthOauthProviderAuthorizeGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>>
export type OauthAuthorizeApiAuthOauthProviderAuthorizeGetSuspenseQueryError = HTTPValidationError


export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Oauth Authorize
 */

export function useOauthAuthorizeApiAuthOauthProviderAuthorizeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthAuthorizeApiAuthOauthProviderAuthorizeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useOauthAuthorizeApiAuthOauthProviderAuthorizeGetSuspenseQueryOptions(provider,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Handle the provider callback and redirect with a one-time login code.
 * @summary Oauth Callback
 */
export const useOauthCallbackApiAuthOauthProviderCallbackGetHook = () => {
        const oauthCallbackApiAuthOauthProviderCallbackGet = useCustomInstance<unknown>();

        return useCallback((
    provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams,
 signal?: AbortSignal
) => {


        return oauthCallbackApiAuthOauthProviderCallbackGet(
          {url: `/api/auth/oauth/${provider}/callback`, method: 'GET',
        params, signal
    },
          );
        }, [oauthCallbackApiAuthOauthProviderCallbackGet])
      }




export const getOauthCallbackApiAuthOauthProviderCallbackGetInfiniteQueryKey = (provider: 'google' | 'github' | 'facebook',
    params?: OauthCallbackApiAuthOauthProviderCallbackGetParams,) => {
    return [
    'infinite', `/api/auth/oauth/${provider}/callback`, ...(params ? [params] : [])
    ] as const;
    }

export const getOauthCallbackApiAuthOauthProviderCallbackGetQueryKey = (provider: 'google' | 'github' | 'facebook',
    params?: OauthCallbackApiAuthOauthProviderCallbackGetParams,) => {
    return [
    `/api/auth/oauth/${provider}/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const useOauthCallbackApiAuthOauthProviderCallbackGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>>, TError = HTTPValidationError>(provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthCallbackApiAuthOauthProviderCallbackGetInfiniteQueryKey(provider,params);

  const oauthCallbackApiAuthOauthProviderCallbackGet =  useOauthCallbackApiAuthOauthProviderCallbackGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>> = ({ signal }) => oauthCallbackApiAuthOauthProviderCallbackGet(provider,params, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OauthCallbackApiAuthOauthProviderCallbackGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>>
export type OauthCallbackApiAuthOauthProviderCallbackGetInfiniteQueryError = HTTPValidationError


export function useOauthCallbackApiAuthOauthProviderCallbackGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthCallbackApiAuthOauthProviderCallbackGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthCallbackApiAuthOauthProviderCallbackGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Oauth Callback
 */

export function useOauthCallbackApiAuthOauthProviderCallbackGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useOauthCallbackApiAuthOauthProviderCallbackGetInfiniteQueryOptions(provider,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const useOauthCallbackApiAuthOauthProviderCallbackGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthCallbackApiAuthOauthProviderCallbackGetQueryKey(provider,params);

  const oauthCallbackApiAuthOauthProviderCallbackGet =  useOauthCallbackApiAuthOauthProviderCallbackGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>> = ({ signal }) => oauthCallbackApiAuthOauthProviderCallbackGet(provider,params, signal);





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OauthCallbackApiAuthOauthProviderCallbackGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>>
export type OauthCallbackApiAuthOauthProviderCallbackGetQueryError = HTTPValidationError


export function useOauthCallbackApiAuthOauthProviderCallbackGet<TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthCallbackApiAuthOauthProviderCallbackGet<TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthCallbackApiAuthOauthProviderCallbackGet<TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Oauth Callback
 */

export function useOauthCallbackApiAuthOauthProviderCallbackGet<TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useOauthCallbackApiAuthOauthProviderCallbackGetQueryOptions(provider,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const useOauthCallbackApiAuthOauthProviderCallbackGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOauthCallbackApiAuthOauthProviderCallbackGetQueryKey(provider,params);

  const oauthCallbackApiAuthOauthProviderCallbackGet =  useOauthCallbackApiAuthOauthProviderCallbackGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>> = ({ signal }) => oauthCallbackApiAuthOauthProviderCallbackGet(provider,params, signal);





   return  queryOptionsBuilder({ queryKey, ...queryOptions, queryFn: queryOptions?.queryFn ?? queryFn}) as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> } & { throwOnError?: ((this: never, error: TError) => boolean) & { readonly __inferenceOnly: never } }
}

export type OauthCallbackApiAuthOauthProviderCallbackGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>>
export type OauthCallbackApiAuthOauthProviderCallbackGetSuspenseQueryError = HTTPValidationError


export function useOauthCallbackApiAuthOauthProviderCallbackGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthCallbackApiAuthOauthProviderCallbackGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOauthCallbackApiAuthOauthProviderCallbackGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Oauth Callback
 */

export function useOauthCallbackApiAuthOauthProviderCallbackGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError = HTTPValidationError>(
 provider: 'google' | 'github' | 'facebook',
    params: OauthCallbackApiAuthOauthProviderCallbackGetParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useOauthCallbackApiAuthOauthProviderCallbackGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useOauthCallbackApiAuthOauthProviderCallbackGetSuspenseQueryOptions(provider,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Exchange a single-use OAuth code for first-party access and refresh tokens.
 * @summary Oauth Exchange
 */
export const useOauthExchangeApiAuthOauthExchangePostHook = () => {
        const oauthExchangeApiAuthOauthExchangePost = useCustomInstance<TokenResponse>();

        return useCallback((
    oAuthExchangeRequest: OAuthExchangeRequest,
 signal?: AbortSignal
) => {


        return oauthExchangeApiAuthOauthExchangePost(
          {url: `/api/auth/oauth/exchange`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: oAuthExchangeRequest, signal
    },
          );
        }, [oauthExchangeApiAuthOauthExchangePost])
      }




export const getOauthExchangeApiAuthOauthExchangePostMutationKey = () => ['oauthExchangeApiAuthOauthExchangePost'] as const;

export const useOauthExchangeApiAuthOauthExchangePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useOauthExchangeApiAuthOauthExchangePostHook>>>, TError,OauthExchangeApiAuthOauthExchangePostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useOauthExchangeApiAuthOauthExchangePostHook>>>, TError,OauthExchangeApiAuthOauthExchangePostMutationVariables, TContext> => {

const mutationKey = getOauthExchangeApiAuthOauthExchangePostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const oauthExchangeApiAuthOauthExchangePost =  useOauthExchangeApiAuthOauthExchangePostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useOauthExchangeApiAuthOauthExchangePostHook>>>, OauthExchangeApiAuthOauthExchangePostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  oauthExchangeApiAuthOauthExchangePost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OauthExchangeApiAuthOauthExchangePostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useOauthExchangeApiAuthOauthExchangePostHook>>>>
    export type OauthExchangeApiAuthOauthExchangePostMutationBody = OAuthExchangeRequest
    export type OauthExchangeApiAuthOauthExchangePostMutationError = HTTPValidationError
    export type OauthExchangeApiAuthOauthExchangePostMutationVariables = {data: OAuthExchangeRequest}

    /**
 * @summary Oauth Exchange
 */
export const useOauthExchangeApiAuthOauthExchangePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useOauthExchangeApiAuthOauthExchangePostHook>>>, TError,OauthExchangeApiAuthOauthExchangePostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useOauthExchangeApiAuthOauthExchangePostHook>>>,
        TError,
        OauthExchangeApiAuthOauthExchangePostMutationVariables,
        TContext
      > => {
      return useMutation(useOauthExchangeApiAuthOauthExchangePostMutationOptions(options), queryClient);
    }
    /**
 * Create options for registering a passkey to the signed-in account.
 * @summary Passkey Registration Options
 */
export const usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostHook = () => {
        const passkeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost = useCustomInstance<PasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost200>();

        return useCallback((

 signal?: AbortSignal
) => {


        return passkeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost(
          {url: `/api/auth/passkeys/register/options`, method: 'POST', signal
    },
          );
        }, [passkeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost])
      }




export const getPasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostMutationKey = () => ['passkeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost'] as const;

export const usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostHook>>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostHook>>>, TError,void, TContext> => {

const mutationKey = getPasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const passkeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost =  usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostHook>>>, void> = () => {


          return  passkeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostHook>>>>

    export type PasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostMutationError = unknown


    /**
 * @summary Passkey Registration Options
 */
export const usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostHook>>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostHook>>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(usePasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostMutationOptions(options), queryClient);
    }
    /**
 * Verify and store a new passkey.
 * @summary Passkey Registration Verify
 */
export const usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostHook = () => {
        const passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPost = useCustomInstance<void>();

        return useCallback((
    passkeyRegistrationVerifyRequest: PasskeyRegistrationVerifyRequest,
 signal?: AbortSignal
) => {


        return passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPost(
          {url: `/api/auth/passkeys/register/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passkeyRegistrationVerifyRequest, signal
    },
          );
        }, [passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPost])
      }




export const getPasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationKey = () => ['passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPost'] as const;

export const usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostHook>>>, TError,PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostHook>>>, TError,PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationVariables, TContext> => {

const mutationKey = getPasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPost =  usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostHook>>>, PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostHook>>>>
    export type PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationBody = PasskeyRegistrationVerifyRequest
    export type PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationError = HTTPValidationError
    export type PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationVariables = {data: PasskeyRegistrationVerifyRequest}

    /**
 * @summary Passkey Registration Verify
 */
export const usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostHook>>>, TError,PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostHook>>>,
        TError,
        PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationVariables,
        TContext
      > => {
      return useMutation(usePasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostMutationOptions(options), queryClient);
    }
    /**
 * Create options for signing in with a passkey.
 * @summary Passkey Authentication Options
 */
export const usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostHook = () => {
        const passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost = useCustomInstance<PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost200>();

        return useCallback((
    passkeyAuthenticationOptionsRequest: PasskeyAuthenticationOptionsRequest,
 signal?: AbortSignal
) => {


        return passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost(
          {url: `/api/auth/passkeys/authenticate/options`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passkeyAuthenticationOptionsRequest, signal
    },
          );
        }, [passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost])
      }




export const getPasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationKey = () => ['passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost'] as const;

export const usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostHook>>>, TError,PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostHook>>>, TError,PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationVariables, TContext> => {

const mutationKey = getPasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost =  usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostHook>>>, PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostHook>>>>
    export type PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationBody = PasskeyAuthenticationOptionsRequest
    export type PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationError = HTTPValidationError
    export type PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationVariables = {data: PasskeyAuthenticationOptionsRequest}

    /**
 * @summary Passkey Authentication Options
 */
export const usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostHook>>>, TError,PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostHook>>>,
        TError,
        PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationVariables,
        TContext
      > => {
      return useMutation(usePasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostMutationOptions(options), queryClient);
    }
    /**
 * Verify a passkey assertion and issue first-party tokens.
 * @summary Passkey Authentication Verify
 */
export const usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostHook = () => {
        const passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPost = useCustomInstance<TokenResponse>();

        return useCallback((
    passkeyAuthenticationVerifyRequest: PasskeyAuthenticationVerifyRequest,
 signal?: AbortSignal
) => {


        return passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPost(
          {url: `/api/auth/passkeys/authenticate/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passkeyAuthenticationVerifyRequest, signal
    },
          );
        }, [passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPost])
      }




export const getPasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationKey = () => ['passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPost'] as const;

export const usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostHook>>>, TError,PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostHook>>>, TError,PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationVariables, TContext> => {

const mutationKey = getPasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPost =  usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostHook>>>, PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostHook>>>>
    export type PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationBody = PasskeyAuthenticationVerifyRequest
    export type PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationError = HTTPValidationError
    export type PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationVariables = {data: PasskeyAuthenticationVerifyRequest}

    /**
 * @summary Passkey Authentication Verify
 */
export const usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostHook>>>, TError,PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostHook>>>,
        TError,
        PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationVariables,
        TContext
      > => {
      return useMutation(usePasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostMutationOptions(options), queryClient);
    }
    /**
 * Refresh access token using refresh token (with rotation).
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshPostHook = () => {
        const refreshTokenApiAuthRefreshPost = useCustomInstance<TokenResponse>();

        return useCallback((
    refreshTokenRequest: RefreshTokenRequest,
 signal?: AbortSignal
) => {


        return refreshTokenApiAuthRefreshPost(
          {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest, signal
    },
          );
        }, [refreshTokenApiAuthRefreshPost])
      }




export const getRefreshTokenApiAuthRefreshPostMutationKey = () => ['refreshTokenApiAuthRefreshPost'] as const;

export const useRefreshTokenApiAuthRefreshPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,RefreshTokenApiAuthRefreshPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,RefreshTokenApiAuthRefreshPostMutationVariables, TContext> => {

const mutationKey = getRefreshTokenApiAuthRefreshPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const refreshTokenApiAuthRefreshPost =  useRefreshTokenApiAuthRefreshPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, RefreshTokenApiAuthRefreshPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  refreshTokenApiAuthRefreshPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenApiAuthRefreshPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>>
    export type RefreshTokenApiAuthRefreshPostMutationBody = RefreshTokenRequest
    export type RefreshTokenApiAuthRefreshPostMutationError = HTTPValidationError
    export type RefreshTokenApiAuthRefreshPostMutationVariables = {data: RefreshTokenRequest}

    /**
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>, TError,RefreshTokenApiAuthRefreshPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useRefreshTokenApiAuthRefreshPostHook>>>,
        TError,
        RefreshTokenApiAuthRefreshPostMutationVariables,
        TContext
      > => {
      return useMutation(useRefreshTokenApiAuthRefreshPostMutationOptions(options), queryClient);
    }
    /**
 * Logout: revoke both the access token and the refresh token.
 * @summary Logout
 */
export const useLogoutApiAuthLogoutPostHook = () => {
        const logoutApiAuthLogoutPost = useCustomInstance<void>();

        return useCallback((
    refreshTokenRequest: RefreshTokenRequest,
 signal?: AbortSignal
) => {


        return logoutApiAuthLogoutPost(
          {url: `/api/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest, signal
    },
          );
        }, [logoutApiAuthLogoutPost])
      }




export const getLogoutApiAuthLogoutPostMutationKey = () => ['logoutApiAuthLogoutPost'] as const;

export const useLogoutApiAuthLogoutPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,LogoutApiAuthLogoutPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,LogoutApiAuthLogoutPostMutationVariables, TContext> => {

const mutationKey = getLogoutApiAuthLogoutPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const logoutApiAuthLogoutPost =  useLogoutApiAuthLogoutPostHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, LogoutApiAuthLogoutPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  logoutApiAuthLogoutPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutApiAuthLogoutPostMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>>
    export type LogoutApiAuthLogoutPostMutationBody = RefreshTokenRequest
    export type LogoutApiAuthLogoutPostMutationError = HTTPValidationError
    export type LogoutApiAuthLogoutPostMutationVariables = {data: RefreshTokenRequest}

    /**
 * @summary Logout
 */
export const useLogoutApiAuthLogoutPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>, TError,LogoutApiAuthLogoutPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useLogoutApiAuthLogoutPostHook>>>,
        TError,
        LogoutApiAuthLogoutPostMutationVariables,
        TContext
      > => {
      return useMutation(useLogoutApiAuthLogoutPostMutationOptions(options), queryClient);
    }
    /**
 * Return the current authenticated user.
 * @summary Get Me
 */
export const useGetMeApiAuthMeGetHook = () => {
        const getMeApiAuthMeGet = useCustomInstance<UserResponse>();

        return useCallback((

 signal?: AbortSignal
) => {


        return getMeApiAuthMeGet(
          {url: `/api/auth/me`, method: 'GET', signal
    },
          );
        }, [getMeApiAuthMeGet])
      }




export const getGetMeApiAuthMeGetInfiniteQueryKey = () => {
    return [
    'infinite', `/api/auth/me`
    ] as const;
    }

export const getGetMeApiAuthMeGetQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const useGetMeApiAuthMeGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiAuthMeGetInfiniteQueryKey();

  const getMeApiAuthMeGet =  useGetMeApiAuthMeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>> = ({ signal }) => getMeApiAuthMeGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiAuthMeGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>
export type GetMeApiAuthMeGetInfiniteQueryError = unknown


export function useGetMeApiAuthMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiAuthMeGetInfinite<TData = InfiniteData<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetMeApiAuthMeGetInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const useGetMeApiAuthMeGetQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiAuthMeGetQueryKey();

  const getMeApiAuthMeGet =  useGetMeApiAuthMeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>> = ({ signal }) => getMeApiAuthMeGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiAuthMeGetQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>
export type GetMeApiAuthMeGetQueryError = unknown


export function useGetMeApiAuthMeGet<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGet<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGet<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiAuthMeGet<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetMeApiAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const useGetMeApiAuthMeGetSuspenseQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiAuthMeGetQueryKey();

  const getMeApiAuthMeGet =  useGetMeApiAuthMeGetHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>> = ({ signal }) => getMeApiAuthMeGet(signal);





   return  queryOptionsBuilder({ queryKey, ...queryOptions, queryFn: queryOptions?.queryFn ?? queryFn}) as UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> } & { throwOnError?: ((this: never, error: TError) => boolean) & { readonly __inferenceOnly: never } }
}

export type GetMeApiAuthMeGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>>
export type GetMeApiAuthMeGetSuspenseQueryError = unknown


export function useGetMeApiAuthMeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiAuthMeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiAuthMeGetSuspense<TData = Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetMeApiAuthMeGetHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetMeApiAuthMeGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






