/**
 * Generated by orval 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Email/password login request.
 */
export interface EmailLoginRequest {
  email: string;
  password: string;
}
