/**
 * Generated by orval 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type OauthCallbackApiAuthOauthProviderCallbackGetParams = {
state: string;
code?: string | null;
error?: string | null;
};
