/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Exchange a one-time OAuth login code for first-party tokens.
 */
export interface OAuthExchangeRequest {
  /**
     * @minLength 32
     * @maxLength 256
     */
  code: string;
  code_verifier?: string | null;
}
