/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams = {
redirect_uri: string;
return_to?: string;
code_challenge?: string | null;
code_challenge_method?: string | null;
};
