/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { PasskeyAuthenticationVerifyRequestCredential } from './passkey-authentication-verify-request-credential';

/**
 * Complete a passkey authentication ceremony.
 */
export interface PasskeyAuthenticationVerifyRequest {
  /**
     * @minLength 32
     * @maxLength 256
     */
  ceremony_id: string;
  credential: PasskeyAuthenticationVerifyRequestCredential;
}
