/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { PasskeyRegistrationVerifyRequestCredential } from './passkey-registration-verify-request-credential';

/**
 * Complete an authenticated passkey registration ceremony.
 */
export interface PasskeyRegistrationVerifyRequest {
  /**
     * @minLength 32
     * @maxLength 256
     */
  ceremony_id: string;
  credential: PasskeyRegistrationVerifyRequestCredential;
}
