/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Start a passkey authentication ceremony.
 */
export interface PasskeyAuthenticationOptionsRequest {
  /**
     * @minLength 3
     * @maxLength 255
     */
  email: string;
}
