/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Email/password registration request.
 */
export interface RegisterRequest {
  email: string;
  password: string;
  name?: string | null;
}
