/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Register with email/password and issue backend tokens.
 * @summary Register
 */
export const RegisterApiAuthRegisterPostBody = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional()
}).describe('Email\/password registration request.')

/**
 * Login with OAuth or email/password and issue backend tokens.

Verify OAuth token, create/update user, and issue JWE tokens.
 * @summary Login
 */
export const LoginApiAuthLoginPostBody = zod.union([zod.object({
  "provider": zod.enum(['google', 'github', 'facebook']),
  "access_token": zod.string(),
  "email": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional()
}).describe('OAuth login request.'),zod.object({
  "email": zod.string(),
  "password": zod.string()
}).describe('Email\/password login request.')])

export const loginApiAuthLoginPostResponseTokenTypeDefault = `bearer`;

export const LoginApiAuthLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(loginApiAuthLoginPostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Exchange better-auth session token for backend JWE tokens.

Used by email/password auth users who have no OAuth provider token.
Verifies session with better-auth server, then issues backend tokens.
 * @summary Session Exchange
 */
export const SessionExchangeApiAuthSessionExchangePostBody = zod.object({
  "session_token": zod.string()
}).describe('Exchange better-auth session token for backend JWE tokens.')

export const sessionExchangeApiAuthSessionExchangePostResponseTokenTypeDefault = `bearer`;

export const SessionExchangeApiAuthSessionExchangePostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(sessionExchangeApiAuthSessionExchangePostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Refresh access token using refresh token.
 * @summary Refresh Token
 */
export const RefreshTokenApiAuthRefreshPostBody = zod.object({
  "refresh_token": zod.string()
}).describe('Refresh token request.')

export const refreshTokenApiAuthRefreshPostResponseTokenTypeDefault = `bearer`;

export const RefreshTokenApiAuthRefreshPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(refreshTokenApiAuthRefreshPostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Return the current authenticated user.
 * @summary Get Me
 */
export const getMeApiAuthMeGetResponseEmailVerifiedDefault = false;

export const GetMeApiAuthMeGetResponse = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "image": zod.union([zod.string(),zod.null()]).optional(),
  "email_verified": zod.boolean().default(getMeApiAuthMeGetResponseEmailVerifiedDefault),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('User response model.')

