/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Register with email/password and issue backend tokens.
 * @summary Register
 */
export const RegisterApiAuthRegisterPostBody = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional()
}).describe('Email\/password registration request.')

/**
 * Login with email/password and issue first-party tokens.
 * @summary Login
 */
export const LoginApiAuthLoginPostBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
}).describe('Email\/password login request.')

export const loginApiAuthLoginPostResponseTokenTypeDefault = `bearer`;

export const LoginApiAuthLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(loginApiAuthLoginPostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Start an OAuth Authorization Code + PKCE transaction.
 * @summary Oauth Authorize
 */
export const OauthAuthorizeApiAuthOauthProviderAuthorizeGetParams = zod.object({
  "provider": zod.enum(['google', 'github', 'facebook'])
})

export const oauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryReturnToDefault = `/`;

export const OauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryParams = zod.object({
  "redirect_uri": zod.string(),
  "return_to": zod.string().default(oauthAuthorizeApiAuthOauthProviderAuthorizeGetQueryReturnToDefault),
  "code_challenge": zod.union([zod.string(),zod.null()]).optional(),
  "code_challenge_method": zod.union([zod.string(),zod.null()]).optional()
})

export const OauthAuthorizeApiAuthOauthProviderAuthorizeGetResponse = zod.unknown()

/**
 * Handle the provider callback and redirect with a one-time login code.
 * @summary Oauth Callback
 */
export const OauthCallbackApiAuthOauthProviderCallbackGetParams = zod.object({
  "provider": zod.enum(['google', 'github', 'facebook'])
})

export const OauthCallbackApiAuthOauthProviderCallbackGetQueryParams = zod.object({
  "state": zod.string(),
  "code": zod.union([zod.string(),zod.null()]).optional(),
  "error": zod.union([zod.string(),zod.null()]).optional()
})

export const OauthCallbackApiAuthOauthProviderCallbackGetResponse = zod.unknown()

/**
 * Exchange a single-use OAuth code for first-party access and refresh tokens.
 * @summary Oauth Exchange
 */
export const oauthExchangeApiAuthOauthExchangePostBodyCodeMin = 32;
export const oauthExchangeApiAuthOauthExchangePostBodyCodeMax = 256;

export const oauthExchangeApiAuthOauthExchangePostBodyCodeVerifierOneMin = 43;
export const oauthExchangeApiAuthOauthExchangePostBodyCodeVerifierOneMax = 128;



export const OauthExchangeApiAuthOauthExchangePostBody = zod.object({
  "code": zod.string().min(oauthExchangeApiAuthOauthExchangePostBodyCodeMin).max(oauthExchangeApiAuthOauthExchangePostBodyCodeMax),
  "code_verifier": zod.union([zod.string().min(oauthExchangeApiAuthOauthExchangePostBodyCodeVerifierOneMin).max(oauthExchangeApiAuthOauthExchangePostBodyCodeVerifierOneMax),zod.null()]).optional()
}).describe('Exchange a one-time OAuth login code for first-party tokens.')

export const oauthExchangeApiAuthOauthExchangePostResponseTokenTypeDefault = `bearer`;

export const OauthExchangeApiAuthOauthExchangePostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(oauthExchangeApiAuthOauthExchangePostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Create options for registering a passkey to the signed-in account.
 * @summary Passkey Registration Options
 */
export const PasskeyRegistrationOptionsApiAuthPasskeysRegisterOptionsPostResponse = zod.record(zod.string(), zod.unknown())

/**
 * Verify and store a new passkey.
 * @summary Passkey Registration Verify
 */
export const passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostBodyCeremonyIdMin = 32;
export const passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostBodyCeremonyIdMax = 256;



export const PasskeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostBody = zod.object({
  "ceremony_id": zod.string().min(passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostBodyCeremonyIdMin).max(passkeyRegistrationVerifyApiAuthPasskeysRegisterVerifyPostBodyCeremonyIdMax),
  "credential": zod.record(zod.string(), zod.unknown())
}).describe('Complete an authenticated passkey registration ceremony.')

/**
 * Create options for signing in with a passkey.
 * @summary Passkey Authentication Options
 */
export const passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostBodyEmailMin = 3;
export const passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostBodyEmailMax = 255;



export const PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostBody = zod.object({
  "email": zod.string().min(passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostBodyEmailMin).max(passkeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostBodyEmailMax)
}).describe('Start a passkey authentication ceremony.')

export const PasskeyAuthenticationOptionsApiAuthPasskeysAuthenticateOptionsPostResponse = zod.record(zod.string(), zod.unknown())

/**
 * Verify a passkey assertion and issue first-party tokens.
 * @summary Passkey Authentication Verify
 */
export const passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostBodyCeremonyIdMin = 32;
export const passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostBodyCeremonyIdMax = 256;



export const PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostBody = zod.object({
  "ceremony_id": zod.string().min(passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostBodyCeremonyIdMin).max(passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostBodyCeremonyIdMax),
  "credential": zod.record(zod.string(), zod.unknown())
}).describe('Complete a passkey authentication ceremony.')

export const passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostResponseTokenTypeDefault = `bearer`;

export const PasskeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(passkeyAuthenticationVerifyApiAuthPasskeysAuthenticateVerifyPostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Refresh access token using refresh token (with rotation).
 * @summary Refresh Token
 */
export const RefreshTokenApiAuthRefreshPostBody = zod.object({
  "refresh_token": zod.string()
}).describe('Refresh token request.')

export const refreshTokenApiAuthRefreshPostResponseTokenTypeDefault = `bearer`;

export const RefreshTokenApiAuthRefreshPostResponse = zod.object({
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "token_type": zod.string().default(refreshTokenApiAuthRefreshPostResponseTokenTypeDefault)
}).describe('Token response.')

/**
 * Logout: revoke both the access token and the refresh token.
 * @summary Logout
 */
export const LogoutApiAuthLogoutPostBody = zod.object({
  "refresh_token": zod.string()
}).describe('Refresh token request.')

/**
 * Return the current authenticated user.
 * @summary Get Me
 */
export const getMeApiAuthMeGetResponseEmailVerifiedDefault = false;

export const GetMeApiAuthMeGetResponse = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "name": zod.union([zod.string(),zod.null()]).optional(),
  "image": zod.union([zod.string(),zod.null()]).optional(),
  "email_verified": zod.boolean().default(getMeApiAuthMeGetResponseEmailVerifiedDefault),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('User response model.')

